import { useCallback, useEffect, useMemo, useState } from "react";
import { Check, ChevronLeft, ChevronRight, Circle, RefreshCw, X } from "lucide-react";
import { ReviewChart, normalizeReviewChart } from "@/pages/ChartMarkerReviewPage";
import { repositories } from "@/services";
import type { ChartMarkerReviewChart, ChartMarkerReviewEvent } from "@/types/chartMarker";
import type { DrctInsightPerformance, DrctInsightPerformanceFilters, DrctInsightPerformanceGroup, DrctInsightPerformanceItem, DrctInsightPerformanceMetric } from "@/types/drctInsight";
import { executionLabel } from "@/utils/drctInsightUx";

type AnalysisTab = "overview" | "gate" | "pattern";
type OutcomeKey = "d0_return" | "d1_return" | "d3_return" | "d5_return" | "mfe_5d" | "mae_5d";
const initialFilters: DrctInsightPerformanceFilters = { period: "60", page: 1, page_size: 50 };

function signed(value: number | null, digits=2) { return value == null ? "-" : `${value > 0 ? "+" : ""}${value.toFixed(digits)}%`; }
function dateLabel(value: string) { return value.replace(/-/g, "."); }
function candidateText(value: string) { return value === "FINAL" ? "검증 후보" : "집중 후보"; }
function outcomeStatus(value: string) { return value === "COMPLETE" ? "평가 완료" : value === "PARTIAL" ? "평가 진행" : "평가 대기"; }
function sampleText(item: DrctInsightPerformanceGroup, title: string) {
  if (item.sample_status === "ACCUMULATING") return title.includes("성공/실패") ? "실패 Marker 비교 사례가 충분해지면 Pattern Edge 구간별 D+5·MFE·MAE를 비교합니다." : "비교 사례를 모으는 중입니다.";
  if (!item.d5.n && item.n) return "D+5 완료 사례가 아직 없어 그룹 간 성과를 비교할 수 없습니다.";
  if (item.sample_status === "INSUFFICIENT") return "표본이 5건 미만이어서 참고용으로만 확인하세요.";
  return "D+5 완료 표본이 모여 그룹 간 성과를 비교할 수 있습니다.";
}
function groupMetric(item: DrctInsightPerformanceGroup, metric: DrctInsightPerformanceMetric, median=false) {
  if (!item.n) return { text: "표본 부족", state: "is-insufficient" };
  if (!metric.n) return { text: "평가 대기", state: "is-pending" };
  return { text: signed(median ? metric.median : metric.mean), state: "" };
}
function groupLabel(title: string, label: string) {
  if (!title.includes("성공 사례 유사도")) return label;
  return ({ "S < 60": "성공 유사도 60 미만", "S 60~69": "성공 유사도 60~69", "S 70~79": "성공 유사도 70~79", "S ≥ 80": "성공 유사도 80 이상" } as Record<string,string>)[label] || label;
}
function metricValue(metric: DrctInsightPerformanceMetric, ratio=false) { if (!metric.n) return "평가 대기"; const value = ratio ? metric.positive_ratio : metric.mean; return value == null ? "-" : ratio ? `${value.toFixed(1)}%` : signed(value); }
function rowOutcome(item: DrctInsightPerformanceItem, key: OutcomeKey, compact=false) { const value=item[key]; if (value != null) return signed(value); return item.outcome_status === "COMPLETE" ? "-" : compact ? "대기" : "평가 대기"; }
function latestOutcomeKey(item: DrctInsightPerformanceItem) {
  if (item.d5_return != null) return "d5_return";
  if (item.d3_return != null) return "d3_return";
  if (item.d1_return != null) return "d1_return";
  if (item.d0_return != null) return "d0_return";
  return null;
}
function markerLink(item: DrctInsightPerformanceItem) { const params=new URLSearchParams({stock_id:String(item.stock_id),marker_date:item.analysis_date,stock_name:item.stock_name}); if(item.theme_id)params.set("theme_id",String(item.theme_id)); return `#/trading/chart-markers?${params.toString()}`; }
function reasonItems(item: DrctInsightPerformanceItem) { return [item.observation_rank ? `${item.theme_name || "연결 테마"} D+1 후보 #${item.observation_rank}` : item.theme_name || "테마 정보 없음", item.success_similarity != null ? `성공 사례 유사도 ${item.success_similarity.toFixed(0)}` : "패턴 평가는 기록 전", candidateText(item.candidate_level), item.flow_gate === "PASS" ? "수급 상태 양호" : null, item.user_status ? `사용자 상태: ${executionLabel(item.user_status)}` : null].filter(Boolean) as string[]; }
function evaluationGuide(data: DrctInsightPerformance | null) { if (!data) return "평가 데이터를 불러오는 중입니다."; if (data.summary.d5.n) return `현재 ${data.summary.d5.n}개 후보의 D+5 평가가 완료되었습니다.`; if (data.summary.d3.n) return `현재 D+3까지 ${data.summary.d3.n}개 후보를 평가했습니다. D+5가 완료되면 MFE·MAE도 확정됩니다.`; if (data.summary.d1.n) return `현재 D+1까지 ${data.summary.d1.n}개 후보를 평가했습니다. 이후 거래일 성과가 순차적으로 누적됩니다.`; return `현재 ${data.summary.d0.n}개 후보의 D0 결과까지 확인했습니다. 다음 거래일부터 D+1 성과가 순차적으로 누적됩니다.`; }

function OutcomeTimeline({ data }: { data: DrctInsightPerformance | null }) {
  const stages=[{label:"D0",metric:data?.summary.d0},{label:"D+1",metric:data?.summary.d1},{label:"D+3",metric:data?.summary.d3},{label:"D+5",metric:data?.summary.d5}];
  return <div className="insight-performance-signal-board" aria-label="후보 성과 평가 진행"><div className="insight-performance-horizons">{stages.map(stage=>{const ready=Boolean(stage.metric?.n);return <article className={ready?"is-ready":"is-waiting"} key={stage.label}><span>{ready?<Check size={13}/>:<Circle size={13}/>}</span><strong>{stage.label}</strong><b>{ready?signed(stage.metric?.mean??null):"대기"}</b><small>{ready?`${stage.metric?.n}건`:"-"}</small></article>;})}</div><div className="insight-performance-signal-metrics"><span><small>MFE 5D</small><strong>{data?metricValue(data.summary.mfe_5d):"대기"}</strong></span><span><small>MAE 5D</small><strong>{data?metricValue(data.summary.mae_5d):"대기"}</strong></span><span><small>D+5 상승</small><strong>{data?metricValue(data.summary.d5,true):"대기"}</strong></span></div></div>;
}

function PerformanceDrawer({ item, onClose }: { item: DrctInsightPerformanceItem; onClose: () => void }) {
  const [chart,setChart]=useState<ChartMarkerReviewChart|null>(null);
  useEffect(()=>{let active=true;setChart(null);repositories.chartMarkers.reviewChart(item.stock_id,item.analysis_date,60,20).then(result=>{if(active)setChart(normalizeReviewChart(result,60,20));}).catch(()=>{if(active)setChart(null);});const escape=(event:KeyboardEvent)=>{if(event.key==="Escape")onClose();};window.addEventListener("keydown",escape);return()=>{active=false;window.removeEventListener("keydown",escape);};},[item.id,item.analysis_date,item.stock_id,onClose]);
  const reviewEvent:ChartMarkerReviewEvent={id:item.marker_event_id??-item.id,stock_id:item.stock_id,marker_id:0,marker_date:item.analysis_date,memo:null,review_result:item.marker_status==="S"||item.marker_status==="F"?item.marker_status:null,reviewed_at:null,marker_name:"DrCT Focus D0",symbol:"D0",marker_group_id:0,group_name:"DrCT Insight",group_color:"#315d9e",stock_code:item.stock_code,stock_name:item.stock_name};
  const reasons=reasonItems(item); const progress=[['D0',item.d0_return],['D+1',item.d1_return],['D+3',item.d3_return],['D+5',item.d5_return]] as const;
  return <div className="insight-performance-drawer-backdrop" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><aside className="insight-performance-drawer" role="dialog" aria-modal="true" aria-label={`${item.stock_name} 후보 성과 상세`}><header><div><small>LIVE CANDIDATE</small><div className="insight-performance-title-row"><h3>{item.stock_name}</h3><strong className={`is-${item.outcome_status.toLowerCase()}`}>{outcomeStatus(item.outcome_status)}</strong></div><p>{item.stock_code} · {item.theme_name||"연결 테마 없음"}</p><span>{dateLabel(item.analysis_date)} · {candidateText(item.candidate_level)}</span></div><button type="button" aria-label="닫기" onClick={onClose}><X size={20}/></button></header><div className="insight-performance-drawer-body">
    <section className="insight-performance-candidate-summary"><span>후보 요약</span><h4>{item.analysis_date.slice(5,7)}월 {item.analysis_date.slice(8,10)}일 {item.theme_name||"연결 테마"}의 {candidateText(item.candidate_level)}로 선정된 종목입니다.</h4><p>D0 {item.d0_return==null?"결과를 확인 중입니다":`${signed(item.d0_return)}로 마감했습니다`} · {item.d1_return==null?"D+1 평가는 대기 중입니다.":`D+1 ${signed(item.d1_return)}를 기록했습니다.`}</p></section>
    <section className="insight-performance-reasons"><h4>선정 당시 이유</h4>{reasons.map(reason=><p key={reason}><Check size={15}/>{reason}</p>)}<details><summary>선정 당시 시스템 값 보기</summary><dl><div><dt>THEME</dt><dd>{item.theme_gate||"기록 전"}</dd></div><div><dt>FLOW</dt><dd>{item.flow_gate||"기록 전"}</dd></div><div><dt>Pattern</dt><dd>{item.pattern_status||"기록 전"}</dd></div><div><dt>US Lead</dt><dd>{item.us_lead_status||"기록 전"}</dd></div><div><dt>Rule Version</dt><dd>{item.insight_rule_version||"기록 전"}</dd></div><div><dt>S / F / Edge</dt><dd>{item.success_similarity?.toFixed(0)||"-"} / {item.failure_similarity?.toFixed(0)||"-"} / {item.pattern_edge?.toFixed(0)||"-"}</dd></div></dl></details></section>
    <section className="insight-performance-results"><h4>실제 결과</h4><dl className="insight-performance-outcomes">{([['D0','d0_return'],['D+1','d1_return'],['D+3','d3_return'],['D+5','d5_return'],['MFE 5D','mfe_5d'],['MAE 5D','mae_5d']] as const).map(([label,key])=><div key={key}><dt>{label}</dt><dd>{rowOutcome(item,key)}</dd></div>)}</dl></section>
    <section className="insight-performance-drawer-progress"><h4>평가 진행</h4><div>{progress.map(([label,value],index)=><article className={value!=null?"is-ready":""} key={label}><span>{value!=null?<Check size={14}/>:<Circle size={14}/>}</span>{index<progress.length-1?<i/>:null}<strong>{label}</strong><small>{value!=null?"완료":"대기"}</small></article>)}</div><p>{item.outcome_status==="COMPLETE"?"D+5와 5거래일 변동폭 평가가 완료되었습니다.":item.d3_return!=null?"현재 D+3까지 확인했습니다. D+5 평가를 기다리고 있습니다.":item.d1_return!=null?"현재 D+1까지 확인했습니다. 이후 거래일 성과가 순차적으로 누적됩니다.":"현재 D0까지 확인했습니다. 다음 거래일부터 평가가 이어집니다."}</p></section>
    <section className="insight-performance-chart"><header><div><h4>D0 전후 가격 흐름</h4><p>집중 후보 선정일 {item.analysis_date} · 점선과 음영은 D0</p></div><a href={markerLink(item)}>Marker 보기 / 기록 <ChevronRight size={15}/></a></header><ReviewChart data={chart} reviewEvent={reviewEvent} loading={!chart} markerEvents={[]} showD0Marker onContextMenu={()=>{}}/></section>
  </div></aside></div>;
}

function GroupPanel({ title, rows }: { title: string; rows: DrctInsightPerformanceGroup[] }) {
  const hasSmallSample=rows.some(item=>item.n<5);
  const accumulating=rows.find(item=>item.sample_status==="ACCUMULATING");
  return <section className="insight-performance-group"><h4>{title}</h4><div className="insight-performance-group-matrix"><div className="insight-performance-group-head"><span>그룹</span><span>표본</span><span>D+5 평균</span><span>중앙값</span><span>MFE</span><span>MAE</span></div>{rows.map(item=>{const d5=groupMetric(item,item.d5);const median=groupMetric(item,item.d5,true);const mfe=groupMetric(item,item.mfe_5d);const mae=groupMetric(item,item.mae_5d);return <article key={item.key}><strong>{groupLabel(title,item.label)}</strong><span>{item.n}건</span><b className={d5.state}>{d5.text}</b><b className={median.state}>{median.text}</b><b className={mfe.state}>{mfe.text}</b><b className={mae.state}>{mae.text}</b></article>;})}</div>{accumulating?<p className="insight-performance-group-note">ⓘ {sampleText(accumulating,title)}</p>:hasSmallSample?<p className="insight-performance-group-note">ⓘ 표본 5건 미만 구간은 참고용입니다.</p>:null}</section>;
}

export default function InsightPerformanceView({ onToday }: { onToday: () => void }) {
  const [filters,setFilters]=useState<DrctInsightPerformanceFilters>(initialFilters); const [data,setData]=useState<DrctInsightPerformance|null>(null); const [selected,setSelected]=useState<DrctInsightPerformanceItem|null>(null); const [tab,setTab]=useState<AnalysisTab>("overview"); const [loading,setLoading]=useState(false),[refreshing,setRefreshing]=useState(false),[error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{setData(await repositories.drctInsight.evaluations(filters));}catch(reason){setError(reason instanceof Error?reason.message:"후보 성과를 불러오지 못했습니다.");}finally{setLoading(false);}},[filters]); useEffect(()=>{void load();},[load]);
  const update=<K extends keyof DrctInsightPerformanceFilters>(key:K,value:DrctInsightPerformanceFilters[K])=>setFilters(current=>({...current,[key]:value,page:key==="page"?Number(value):1}));
  const refresh=async()=>{setRefreshing(true);setError("");try{await repositories.drctInsight.refreshEvaluations();await load();}catch(reason){setError(reason instanceof Error?reason.message:"성과 갱신에 실패했습니다.");}finally{setRefreshing(false);}};
  const progressCount=(data?.summary.pending_count||0)+(data?.summary.partial_count||0);
  return <div className="insight-performance-view insight-performance-ux"><nav className="insight-secondary-nav" aria-label="Insight 화면 전환"><button type="button" onClick={onToday}>오늘의 판단</button><button type="button" className="is-active">후보 성과</button><b>LIVE / ACTUAL</b></nav>
    <header className="insight-performance-head"><div><h2>후보 성과</h2><p>선정 후보의 D0부터 D+5까지 실제 움직임을 비교합니다.</p></div><button type="button" className="btn btn-secondary" disabled={refreshing} onClick={()=>void refresh()}><RefreshCw size={16}/>{refreshing?"갱신 중":"성과 갱신"}</button></header>
    {error?<div className="insight-error">{error}<button type="button" onClick={()=>void load()}>다시 시도</button></div>:null}
    <section className="insight-performance-summary"><div className="insight-performance-summary-strip"><dl className="insight-performance-counts"><div><dt>전체</dt><dd>{data?.summary.total_count??"-"}</dd></div><div><dt>완료</dt><dd>{data?.summary.complete_count??"-"}</dd></div><div><dt>진행</dt><dd>{progressCount}</dd></div><div><dt>대기</dt><dd>{data?.summary.pending_count??"-"}</dd></div></dl><span>최근 평가 {data?.latest_evaluated_at?.slice(0,16)||"-"}</span></div><OutcomeTimeline data={data}/><p className="insight-performance-guide">ⓘ {evaluationGuide(data)}</p></section>
    <section className="insight-performance-analysis"><nav>{([['overview','전체 성과'],['gate','조건별 성과'],['pattern','패턴별 성과']] as const).map(([key,label])=><button type="button" className={tab===key?"is-active":""} key={key} onClick={()=>setTab(key)}>{label}</button>)}</nav>{tab==="overview"?<p className="insight-performance-objective">후보 선정 이후의 실제 움직임만 보여줍니다. 아직 도래하지 않은 거래일은 ‘평가 대기’로 구분합니다.</p>:null}{tab==="gate"?<><p className="insight-performance-objective">수급·미국 선행·D+1 후보·집중순위별로 이후 D+5 성과 차이가 있었는지 비교합니다.</p><div className="insight-performance-groups"><GroupPanel title="수급 상태별" rows={data?.groups.flow||[]}/><GroupPanel title="미국 선행 여부" rows={data?.groups.us_lead||[]}/><GroupPanel title="D+1 후보순위별" rows={data?.groups.observation_rank||[]}/><GroupPanel title="집중순위별" rows={data?.groups.focus_rank||[]}/></div></>:null}{tab==="pattern"?<><p className="insight-performance-objective">과거 성공 차트와의 유사도가 높을수록 실제 이후 성과가 좋았는지 확인합니다. 성공/실패 비교는 실패 Marker 사례가 더 축적되면 분석됩니다.</p><div className="insight-performance-groups"><GroupPanel title="성공 사례 유사도별 성과" rows={data?.groups.success_similarity||[]}/><GroupPanel title="성공/실패 구분력별 성과" rows={data?.groups.pattern_edge||[]}/></div></>:null}</section>
    <section className="insight-performance-table-section"><div className="insight-performance-filters"><label><span>기간</span><select aria-label="성과 기간" value={filters.period} onChange={event=>update("period",event.target.value as DrctInsightPerformanceFilters["period"])}><option value="20">20거래일</option><option value="60">60거래일</option><option value="120">120거래일</option><option value="ALL">전체</option></select></label><label><span>후보</span><select aria-label="후보 등급" value={filters.candidate_level||""} onChange={event=>update("candidate_level",event.target.value as "FOCUS"|"FINAL"||undefined)}><option value="">전체</option><option value="FOCUS">집중 후보</option><option value="FINAL">검증 후보</option></select></label><label><span>테마</span><select aria-label="테마" value={filters.theme_id||""} onChange={event=>update("theme_id",Number(event.target.value)||undefined)}><option value="">전체</option>{data?.themes.map(theme=><option key={theme.id} value={theme.id}>{theme.name}</option>)}</select></label><label><span>패턴</span><select aria-label="Pattern 상태" value={filters.pattern_status||""} onChange={event=>update("pattern_status",event.target.value||undefined)}><option value="">전체</option>{["VERIFIED","PROMISING","WATCH","WEAK","NOT_READY"].map(value=><option key={value}>{value}</option>)}</select></label><label><span>평가 상태</span><select aria-label="Outcome 상태" value={filters.outcome_status||""} onChange={event=>update("outcome_status",event.target.value as DrctInsightPerformanceFilters["outcome_status"]||undefined)}><option value="">전체</option><option value="PENDING">평가 대기</option><option value="PARTIAL">평가 진행</option><option value="COMPLETE">평가 완료</option></select></label></div>
      <div className="insight-performance-table"><table><thead><tr><th>기준일</th><th>종목 / 테마</th><th>선정 이유</th><th>D0</th><th>D+1</th><th>D+3</th><th>D+5</th><th>MFE</th><th>MAE</th><th>상태</th></tr></thead><tbody>{data?.items.map(item=>{const latest=latestOutcomeKey(item);return <tr key={item.id} tabIndex={0} onClick={()=>setSelected(item)} onKeyDown={event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();setSelected(item);}}}><td data-label="기준일">{item.analysis_date.slice(5)}</td><td data-label="종목 / 테마"><strong>{item.stock_name}</strong><small>{item.theme_name||"연결 테마 없음"} · {candidateText(item.candidate_level)}{item.focus_rank?` #${item.focus_rank}`:""}</small></td><td data-label="선정 이유"><span className="insight-performance-reason">성공 유사 {item.success_similarity?.toFixed(0)||"-"}{item.observation_rank?` · 테마 #${item.observation_rank}`:""}</span></td>{(["d0_return","d1_return","d3_return","d5_return","mfe_5d","mae_5d"] as OutcomeKey[]).map(key=><td className={`insight-performance-number ${latest===key?"is-latest":""}`} data-label={key.toUpperCase()} title={item[key]==null&&item.outcome_status!=="COMPLETE"?"아직 해당 거래일이 도래하지 않았습니다.":undefined} key={key}>{rowOutcome(item,key,true)}</td>)}<td data-label="상태"><span className={`insight-performance-status is-${item.outcome_status.toLowerCase()}`}>{outcomeStatus(item.outcome_status)}</span></td></tr>;})}</tbody></table>{!loading&&!data?.items.length?<div className="insight-empty">해당 조건의 후보가 없습니다.</div>:null}</div><footer className="insight-performance-pagination"><span>총 {data?.total??0}건</span><select aria-label="페이지 크기" value={filters.page_size} onChange={event=>update("page_size",Number(event.target.value) as 20|50|100)}><option value={20}>20개</option><option value={50}>50개</option><option value={100}>100개</option></select><button type="button" aria-label="이전 페이지" disabled={filters.page<=1} onClick={()=>update("page",filters.page-1)}><ChevronLeft size={16}/></button><b>{data?.page??1} / {data?.total_pages??1}</b><button type="button" aria-label="다음 페이지" disabled={!data||filters.page>=data.total_pages} onClick={()=>update("page",filters.page+1)}><ChevronRight size={16}/></button></footer></section>
    {selected?<PerformanceDrawer item={selected} onClose={()=>setSelected(null)}/>:null}
  </div>;
}
