from __future__ import annotations

import json
from typing import Any


def json_text(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False)


BASE_OPERATORS = [">", ">=", "<", "<=", "between", "=", "!="]


DEFAULT_ANALYSIS_INDICATORS: list[dict[str, Any]] = [
    {"indicator_key": "open_price", "indicator_name": "시가", "description": "일봉 시가", "source_type": "db_column", "source_table": "stock_daily_prices", "source_column": "open_price", "data_type": "number", "unit": "원", "category": "price", "sort_order": 10},
    {"indicator_key": "high_price", "indicator_name": "고가", "description": "일봉 고가", "source_type": "db_column", "source_table": "stock_daily_prices", "source_column": "high_price", "data_type": "number", "unit": "원", "category": "price", "sort_order": 20},
    {"indicator_key": "low_price", "indicator_name": "저가", "description": "일봉 저가", "source_type": "db_column", "source_table": "stock_daily_prices", "source_column": "low_price", "data_type": "number", "unit": "원", "category": "price", "sort_order": 30},
    {"indicator_key": "close_price", "indicator_name": "종가", "description": "일봉 종가", "source_type": "db_column", "source_table": "stock_daily_prices", "source_column": "close_price", "data_type": "number", "unit": "원", "category": "price", "sort_order": 40},
    {"indicator_key": "volume", "indicator_name": "거래량", "description": "일봉 거래량", "source_type": "db_column", "source_table": "stock_daily_prices", "source_column": "volume", "data_type": "number", "unit": "주", "category": "volume", "sort_order": 50},
    {"indicator_key": "trading_value", "indicator_name": "거래대금", "description": "일봉 거래대금", "source_type": "db_column", "source_table": "stock_daily_prices", "source_column": "trading_value", "data_type": "number", "unit": "원", "category": "trading_value", "sort_order": 60},
    {"indicator_key": "prev_volume", "indicator_name": "전일 거래량", "description": "직전 거래일 거래량", "source_type": "calculated", "calculation_formula": "previous(volume)", "required_columns_json": json_text(["volume"]), "data_type": "number", "unit": "주", "category": "volume", "sort_order": 100},
    {"indicator_key": "volume_vs_prev_day", "indicator_name": "전일 대비 거래량 배수", "description": "오늘 거래량이 전일 거래량의 몇 배인지", "source_type": "calculated", "calculation_formula": "volume / prev_volume", "required_columns_json": json_text(["volume"]), "data_type": "ratio", "unit": "배", "category": "volume", "default_operator": ">=", "default_value_json": json_text(2), "sort_order": 110},
    {"indicator_key": "prev_trading_value", "indicator_name": "전일 거래대금", "description": "직전 거래일 거래대금", "source_type": "calculated", "calculation_formula": "previous(trading_value)", "required_columns_json": json_text(["trading_value"]), "data_type": "number", "unit": "원", "category": "trading_value", "sort_order": 120},
    {"indicator_key": "trading_value_vs_prev_day", "indicator_name": "전일 대비 거래대금 배수", "description": "오늘 거래대금이 전일 거래대금의 몇 배인지", "source_type": "calculated", "calculation_formula": "trading_value / prev_trading_value", "required_columns_json": json_text(["trading_value"]), "data_type": "ratio", "unit": "배", "category": "trading_value", "sort_order": 130},
    *[
        {"indicator_key": f"ma{period}", "indicator_name": f"{period}일 이동평균", "description": f"종가 기준 {period}일 단순 이동평균", "source_type": "calculated", "calculation_formula": f"avg(close_price, {period})", "required_columns_json": json_text(["close_price"]), "data_type": "number", "unit": "원", "category": "moving_average", "sort_order": 200 + period}
        for period in (5, 10, 20, 60, 120)
    ],
    {"indicator_key": "close_vs_ma20_pct", "indicator_name": "20일선 이격률", "description": "종가와 20일 이동평균의 거리", "source_type": "calculated", "calculation_formula": "(close_price - ma20) / ma20 * 100", "required_columns_json": json_text(["close_price"]), "data_type": "percent", "unit": "%", "category": "moving_average", "default_operator": "between", "default_value_json": json_text([-3, 3]), "sort_order": 330},
    {"indicator_key": "close_vs_ma60_pct", "indicator_name": "60일선 이격률", "description": "종가와 60일 이동평균의 거리", "source_type": "calculated", "calculation_formula": "(close_price - ma60) / ma60 * 100", "required_columns_json": json_text(["close_price"]), "data_type": "percent", "unit": "%", "category": "moving_average", "sort_order": 340},
    {"indicator_key": "volume_ma20", "indicator_name": "거래량 20일 평균", "description": "20일 평균 거래량", "source_type": "calculated", "calculation_formula": "avg(volume, 20)", "required_columns_json": json_text(["volume"]), "data_type": "number", "unit": "주", "category": "volume", "sort_order": 350},
    {"indicator_key": "volume_ratio_20", "indicator_name": "거래량 20일 평균 배수", "description": "당일 거래량이 20일 평균의 몇 배인지", "source_type": "calculated", "calculation_formula": "volume / volume_ma20", "required_columns_json": json_text(["volume"]), "data_type": "ratio", "unit": "배", "category": "volume", "default_operator": ">=", "default_value_json": json_text(2), "sort_order": 360},
    {"indicator_key": "trading_value_ma20", "indicator_name": "거래대금 20일 평균", "description": "20일 평균 거래대금", "source_type": "calculated", "calculation_formula": "avg(trading_value, 20)", "required_columns_json": json_text(["trading_value"]), "data_type": "number", "unit": "원", "category": "trading_value", "sort_order": 370},
    {"indicator_key": "trading_value_ratio_20", "indicator_name": "거래대금 20일 평균 배수", "description": "당일 거래대금이 20일 평균의 몇 배인지", "source_type": "calculated", "calculation_formula": "trading_value / trading_value_ma20", "required_columns_json": json_text(["trading_value"]), "data_type": "ratio", "unit": "배", "category": "trading_value", "default_operator": ">=", "default_value_json": json_text(1.3), "sort_order": 380},
    {"indicator_key": "return_1d", "indicator_name": "1일 수익률", "description": "전일 종가 대비 수익률", "source_type": "calculated", "calculation_formula": "return(close_price, 1)", "required_columns_json": json_text(["close_price"]), "data_type": "percent", "unit": "%", "category": "return", "sort_order": 390},
    {"indicator_key": "recent_3d_return", "indicator_name": "최근 3일 수익률", "description": "최근 3거래일 종가 수익률", "source_type": "calculated", "calculation_formula": "return(close_price, 3)", "required_columns_json": json_text(["close_price"]), "data_type": "percent", "unit": "%", "category": "return", "default_operator": ">=", "default_value_json": json_text(15), "sort_order": 400},
    {"indicator_key": "recent_5d_return", "indicator_name": "최근 5일 수익률", "description": "최근 5거래일 종가 수익률", "source_type": "calculated", "calculation_formula": "return(close_price, 5)", "required_columns_json": json_text(["close_price"]), "data_type": "percent", "unit": "%", "category": "return", "sort_order": 410},
    {"indicator_key": "ma60_5d_ago", "indicator_name": "5거래일 전 60일선", "description": "5거래일 전 60일 이동평균", "source_type": "calculated", "calculation_formula": "ma60 at D-5", "required_columns_json": json_text(["close_price"]), "data_type": "number", "unit": "원", "category": "trend", "sort_order": 420},
    {"indicator_key": "ma60_20d_ago", "indicator_name": "20거래일 전 60일선", "description": "20거래일 전 60일 이동평균", "source_type": "calculated", "calculation_formula": "ma60 at D-20", "required_columns_json": json_text(["close_price"]), "data_type": "number", "unit": "원", "category": "trend", "sort_order": 430},
    {"indicator_key": "ma60_slope_5d", "indicator_name": "60일선 5일 기울기", "description": "현재 60일선과 5거래일 전 60일선의 차이", "source_type": "calculated", "calculation_formula": "ma60 - ma60_5d_ago", "required_columns_json": json_text(["close_price"]), "data_type": "number", "unit": "원", "category": "trend", "default_operator": ">", "default_value_json": json_text(0), "sort_order": 440},
    {"indicator_key": "ma60_slope_20d", "indicator_name": "60일선 20일 기울기", "description": "현재 60일선과 20거래일 전 60일선의 차이", "source_type": "calculated", "calculation_formula": "ma60 - ma60_20d_ago", "required_columns_json": json_text(["close_price"]), "data_type": "number", "unit": "원", "category": "trend", "sort_order": 450},
    {"indicator_key": "is_ma60_rising_5d", "indicator_name": "60일선 5일 상승 여부", "description": "60일선 5일 기울기가 양수인지", "source_type": "calculated", "calculation_formula": "ma60_slope_5d > 0", "required_columns_json": json_text(["close_price"]), "data_type": "boolean", "unit": "boolean", "category": "trend", "sort_order": 460},
    {"indicator_key": "is_ma60_rising_20d", "indicator_name": "60일선 20일 상승 여부", "description": "60일선 20일 기울기가 양수인지", "source_type": "calculated", "calculation_formula": "ma60_slope_20d > 0", "required_columns_json": json_text(["close_price"]), "data_type": "boolean", "unit": "boolean", "category": "trend", "sort_order": 470},
    {"indicator_key": "close_above_previous_high", "indicator_name": "전일 고가 돌파", "description": "종가가 전일 고가를 돌파했는지", "source_type": "calculated", "calculation_formula": "close_price > previous(high_price)", "required_columns_json": json_text(["close_price", "high_price"]), "data_type": "boolean", "unit": "boolean", "category": "candle", "sort_order": 480},
    {"indicator_key": "close_between_ma10_ma20", "indicator_name": "종가 10일선과 20일선 사이", "description": "종가가 10일선과 20일선 사이에 있는지", "source_type": "calculated", "calculation_formula": "min(ma10, ma20) <= close_price <= max(ma10, ma20)", "required_columns_json": json_text(["close_price"]), "data_type": "boolean", "unit": "boolean", "category": "condition", "default_operator": "=", "default_value_json": json_text(True), "sort_order": 490},
    {"indicator_key": "max_future_return_5d", "indicator_name": "5거래일 최대상승률", "description": "진입 후 5거래일 내 고가 기준 최대 수익률", "source_type": "calculated", "calculation_formula": "max(future high, 5d)", "required_columns_json": json_text(["high_price", "close_price"]), "data_type": "percent", "unit": "%", "category": "future_result", "is_entry_allowed": 0, "is_success_allowed": 1, "sort_order": 900},
    {"indicator_key": "min_future_return_5d", "indicator_name": "5거래일 최대하락률", "description": "진입 후 5거래일 내 저가 기준 최대 하락률", "source_type": "calculated", "calculation_formula": "min(future low, 5d)", "required_columns_json": json_text(["low_price", "close_price"]), "data_type": "percent", "unit": "%", "category": "future_result", "is_entry_allowed": 0, "is_failure_allowed": 1, "sort_order": 910},
    {"indicator_key": "future_return_5d", "indicator_name": "5거래일 종가수익률", "description": "진입 후 5거래일 뒤 종가 기준 수익률", "source_type": "calculated", "calculation_formula": "future close return, 5d", "required_columns_json": json_text(["close_price"]), "data_type": "percent", "unit": "%", "category": "future_result", "is_entry_allowed": 0, "is_success_allowed": 1, "is_failure_allowed": 1, "sort_order": 920},
    {"indicator_key": "max_future_return_nd", "indicator_name": "N거래일 최대상승률", "description": "진입 후 N거래일 내 고가 기준 최대 수익률", "source_type": "calculated", "calculation_formula": "max(future high, Nd)", "required_columns_json": json_text(["high_price", "close_price"]), "data_type": "percent", "unit": "%", "category": "future_result", "is_entry_allowed": 0, "is_success_allowed": 1, "sort_order": 930},
    {"indicator_key": "min_future_return_nd", "indicator_name": "N거래일 최대하락률", "description": "진입 후 N거래일 내 저가 기준 최대 하락률", "source_type": "calculated", "calculation_formula": "min(future low, Nd)", "required_columns_json": json_text(["low_price", "close_price"]), "data_type": "percent", "unit": "%", "category": "future_result", "is_entry_allowed": 0, "is_failure_allowed": 1, "sort_order": 940},
]


DEFAULT_ANALYSIS_ALIASES: list[dict[str, Any]] = [
    {"alias_text": "20일선", "indicator_key": "ma20", "default_category": "reference", "description": "20일 이동평균선", "sort_order": 10},
    {"alias_text": "20일선 근처", "indicator_key": "close_vs_ma20_pct", "default_operator": "between", "default_value_json": json_text([-3, 3]), "default_category": "entry_filter", "needs_review": 1, "sort_order": 20},
    {"alias_text": "20일선 눌림", "indicator_key": "close_vs_ma20_pct", "default_operator": "between", "default_value_json": json_text([-3, 3]), "default_category": "entry_filter", "needs_review": 1, "sort_order": 30},
    {"alias_text": "눌림목", "indicator_key": "close_vs_ma20_pct", "default_operator": "between", "default_value_json": json_text([-3, 3]), "default_category": "entry_filter", "needs_review": 1, "sort_order": 40},
    {"alias_text": "60일선 상승", "indicator_key": "ma60_slope_5d", "default_operator": ">", "default_value_json": json_text(0), "default_category": "entry_filter", "apply_to_samples_default": 1, "needs_review": 1, "sort_order": 50},
    {"alias_text": "상승추세", "indicator_key": "ma60_slope_5d", "default_operator": ">", "default_value_json": json_text(0), "default_category": "entry_filter", "needs_review": 1, "sort_order": 60},
    {"alias_text": "거래량 증가", "indicator_key": "volume_ratio_20", "default_operator": ">=", "default_value_json": json_text(1.3), "default_category": "entry_filter", "needs_review": 1, "sort_order": 70},
    {"alias_text": "거래량 전날 2배", "indicator_key": "volume_vs_prev_day", "default_operator": ">=", "default_value_json": json_text(2), "default_category": "entry_filter", "apply_to_samples_default": 1, "needs_review": 0, "sort_order": 80},
    {"alias_text": "거래량 20일 평균 2배", "indicator_key": "volume_ratio_20", "default_operator": ">=", "default_value_json": json_text(2), "default_category": "entry_filter", "needs_review": 0, "sort_order": 90},
    {"alias_text": "거래량 2배", "indicator_key": "volume_vs_prev_day", "default_operator": ">=", "default_value_json": json_text(2), "default_category": "entry_filter", "needs_review": 1, "description": "전일 대비인지 20일 평균 대비인지 확인 필요", "sort_order": 100},
    {"alias_text": "거래대금 증가", "indicator_key": "trading_value_ratio_20", "default_operator": ">=", "default_value_json": json_text(1.3), "default_category": "entry_filter", "needs_review": 1, "sort_order": 110},
    {"alias_text": "거래대금 재유입", "indicator_key": "trading_value_ratio_20", "default_operator": ">=", "default_value_json": json_text(1.3), "default_category": "entry_filter", "needs_review": 1, "sort_order": 120},
    {"alias_text": "거래대금이 다시 유입", "indicator_key": "trading_value_ratio_20", "default_operator": ">=", "default_value_json": json_text(1.3), "default_category": "entry_filter", "needs_review": 1, "sort_order": 125},
    {"alias_text": "수급 유입", "indicator_key": "trading_value_ratio_20", "default_operator": ">=", "default_value_json": json_text(1.3), "default_category": "entry_filter", "needs_review": 1, "sort_order": 130},
    {"alias_text": "급등 직후 제외", "indicator_key": "recent_3d_return", "default_operator": ">=", "default_value_json": json_text(15), "default_category": "exclude_filter", "apply_to_samples_default": 1, "needs_review": 1, "sort_order": 140},
    {"alias_text": "추격매수 제외", "indicator_key": "recent_3d_return", "default_operator": ">=", "default_value_json": json_text(15), "default_category": "exclude_filter", "apply_to_samples_default": 1, "needs_review": 1, "sort_order": 150},
    {"alias_text": "과열 제외", "indicator_key": "recent_3d_return", "default_operator": ">=", "default_value_json": json_text(15), "default_category": "exclude_filter", "needs_review": 1, "sort_order": 160},
    {"alias_text": "종가 10일선과 20일선 사이", "indicator_key": "close_between_ma10_ma20", "default_operator": "=", "default_value_json": json_text(True), "default_category": "entry_filter", "apply_to_samples_default": 1, "needs_review": 0, "sort_order": 170},
    {"alias_text": "10일선과 20일선 사이", "indicator_key": "close_between_ma10_ma20", "default_operator": "=", "default_value_json": json_text(True), "default_category": "entry_filter", "apply_to_samples_default": 1, "needs_review": 0, "sort_order": 175},
    {"alias_text": "이평선 사이", "indicator_key": "close_between_ma10_ma20", "default_operator": "=", "default_value_json": json_text(True), "default_category": "entry_filter", "needs_review": 1, "sort_order": 180},
]


DEFAULT_ANALYSIS_CONDITION_TEMPLATES: list[dict[str, Any]] = [
    {"template_key": "pullback_near_ma20", "template_name": "20일선 눌림", "description": "20일선 근처에서 최근 조정을 받은 패턴", "template_type": "entry_filter", "condition_json": json_text({"conditions": [{"indicator_key": "close_vs_ma20_pct", "operator": "between", "value": [-3, 3]}, {"indicator_key": "recent_5d_return", "operator": "<=", "value": 0}]}), "needs_review": 1, "sort_order": 10},
    {"template_key": "trading_value_reentry", "template_name": "거래대금 재유입", "description": "20일 평균 대비 거래대금 증가", "template_type": "entry_filter", "condition_json": json_text({"conditions": [{"indicator_key": "trading_value_ratio_20", "operator": ">=", "value": 1.3}]}), "needs_review": 1, "sort_order": 20},
    {"template_key": "exclude_recent_surge", "template_name": "급등 직후 제외", "description": "최근 3일 수익률 과열 구간 제외", "template_type": "exclude_filter", "condition_json": json_text({"conditions": [{"indicator_key": "recent_3d_return", "operator": ">=", "value": 15}]}), "default_apply_to_samples": 1, "needs_review": 1, "sort_order": 30},
    {"template_key": "ma60_uptrend", "template_name": "60일선 상승추세", "description": "60일 이동평균 5일 기울기 양수", "template_type": "entry_filter", "condition_json": json_text({"conditions": [{"indicator_key": "ma60_slope_5d", "operator": ">", "value": 0}]}), "default_apply_to_samples": 1, "needs_review": 1, "sort_order": 40},
    {"template_key": "close_between_ma10_ma20", "template_name": "종가 10일선과 20일선 사이", "description": "종가가 10일선과 20일선 사이", "template_type": "entry_filter", "condition_json": json_text({"conditions": [{"indicator_key": "close_between_ma10_ma20", "operator": "=", "value": True}]}), "default_apply_to_samples": 1, "needs_review": 0, "sort_order": 50},
]
