import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { AlertTriangle, Check, ChevronRight, RefreshCw, Star, X } from "lucide-react";
import PageHeader from "@/components/common/PageHeader";
import { repositories } from "@/services";
import type { CandidateLevel, DrctInsightReviewItem, DrctInsightStock, DrctInsightTheme, DrctInsightToday, DrctInsightUsLead, DrctInsightWatchItem, InsightGates, IntradayState, PatternStatus, ReadinessStatus } from "@/types/drctInsight";
import { buildNaverStockCandleChartUrl, getNaverChartSessionSidcode, type NaverStockCandlePeriod } from "@/utils/naverChart";

type StockSort = "candidate" | "pattern" | "change";
type CandidateFilter = "ALL" | "FOCUS" | "PRELIMINARY" | "FINAL";
type WatchFilter = "ALL" | "READY" | "WATCH" | "TRIGGERED";
type ReviewFilter = "ALL" | "STRONG" | "WEAK" | "MISMATCH" | "UNRECORDED";
type DrawerTab = "summary" | "pattern" | "flow" | "chart";
type ThemeSnapshot = { changeRate: number | null; strength: number | null; valid: number; linked: number };
type InsightSnapshot = { themes: Record<number, ThemeSnapshot> };
type IntradayView = { state: IntradayState; reasons: string[]; themeDelta: number | null; themeChangeDelta: number | null; initialThemeDelta: number | null; breadthDelta: number | null; executionAssist: "CONSIDER_READY" | "KEEP_WATCH" | "CAUTION" };

const gateLabel: Record<string, string> = { PASS: "PASS", WATCH: "WATCH", WEAK: "WEAK", NO_DATA: "NO DATA", NOT_READY: "NOT READY", WAIT: "WAIT", READY: "READY", TRIGGERED: "TRIGGERED", INVALID: "INVALID", VERIFIED: "VERIFIED", PROMISING: "PROMISING" };
const executionStatus: Record<string, string> = { WAIT: "관심", READY: "매수후보", TRIGGERED: "보유중", INVALID: "제외" };
const freshnessLabel: Record<string, string> = { domestic_theme: "국내 테마", observation: "관찰순위", us_kr: "미국 테마", stock_signal: "종목시그널", realtime: "실시간" };
const readinessLabel: Record<string, string> = { theme: "THEME", flow: "FLOW", us_kr: "US → KR", pattern: "PATTERN", realtime: "REALTIME", outcome: "OUTCOME" };

function number(value: number | null, digits = 0) { return value == null ? "-" : value.toFixed(digits); }
function pct(value: number | null, digits = 1) { return value == null ? "-" : `${value > 0 ? "+" : ""}${value.toFixed(digits)}%`; }
function point(value: number | null, digits = 1) { return value == null ? "-" : `${value > 0 ? "+" : ""}${value.toFixed(digits)}`; }
function delta(current: number | null, previous: number | null) { return current == null || previous == null ? null : current - previous; }
function movement(value: number | null, suffix = "") { return value == null ? "" : `${value > 0 ? "▲" : value < 0 ? "▼" : "→"} ${point(value)}${suffix}`; }
function snapshotOf(data: DrctInsightToday): InsightSnapshot { return { themes: Object.fromEntries(data.themes.map((row) => [row.theme_id, { changeRate: row.change_rate, strength: row.theme_strength, valid: row.valid_stock_count, linked: row.linked_stock_count }])) }; }

function intradayView(stock: DrctInsightStock, previous: InsightSnapshot | null, initial: InsightSnapshot | null, priorState: IntradayState = "STABLE"): IntradayView {
  const currentThemeValue = stock.theme_strength ?? stock.theme_change_rate;
  const previousTheme = stock.theme_id == null ? null : previous?.themes[stock.theme_id];
  const initialTheme = stock.theme_id == null ? null : initial?.themes[stock.theme_id];
  const themeDelta = delta(currentThemeValue, previousTheme?.strength ?? previousTheme?.changeRate ?? null);
  const themeChangeDelta = delta(stock.theme_change_rate, previousTheme?.changeRate ?? null);
  const initialThemeDelta = delta(currentThemeValue, initialTheme?.strength ?? initialTheme?.changeRate ?? null);
  const breadthDelta = previousTheme ? stock.theme_valid_stock_count - previousTheme.valid : null;
  const relative = stock.relative_strength;
  let proposed: IntradayState = "STABLE";
  if ((themeDelta != null && themeDelta <= -1) || (breadthDelta != null && breadthDelta <= -3) || (relative != null && relative <= -2)) proposed = "WARNING";
  else if ((themeDelta != null && themeDelta <= -.3) || (breadthDelta != null && breadthDelta <= -1) || (relative != null && relative <= -.5)) proposed = "WEAKENING";
  else if (themeDelta != null && themeDelta >= .3 && (breadthDelta == null || breadthDelta >= 0) && relative != null && relative >= .5) proposed = "STRENGTHENING";
  if (proposed === "STABLE" && priorState === "STRENGTHENING" && ((themeDelta ?? 0) >= .1 || (breadthDelta ?? 0) > 0)) proposed = priorState;
  if (proposed === "STABLE" && priorState === "WEAKENING" && ((themeDelta ?? 0) <= -.1 || (breadthDelta ?? 0) < 0)) proposed = priorState;
  const reasons = previous ? [themeDelta == null ? "테마강도 비교 대기" : `테마강도 ${movement(themeDelta, "%p")}`, themeChangeDelta == null ? "테마 등락 비교 대기" : `테마 등락 ${movement(themeChangeDelta, "%p")}`, breadthDelta == null ? "확산 비교 대기" : `확산 ${previousTheme?.valid}/${previousTheme?.linked} → ${stock.theme_valid_stock_count}/${stock.theme_linked_stock_count}`, `종목 상대강도 ${point(relative)}%p`] : ["최초 진입 Snapshot 설정", `종목 상대강도 ${point(relative)}%p`];
  const executionAssist = proposed === "WARNING" ? "CAUTION" : proposed === "STRENGTHENING" ? "CONSIDER_READY" : "KEEP_WATCH";
  return { state: proposed, reasons, themeDelta, themeChangeDelta, initialThemeDelta, breadthDelta, executionAssist };
}

function Gate({ label, value }: { label: string; value?: string | null }) { const resolved = value || "NO_DATA"; return <span className={`insight-gate insight-gate--${resolved.toLowerCase().replace(/_/g, "-")}`}><b>{label}</b><span>{["PASS", "VERIFIED"].includes(resolved) ? <Check size={12} /> : null}{gateLabel[resolved] || resolved}</span></span>; }
function GateRow({ gates, patternStatus, execution = true }: { gates: InsightGates; patternStatus?: PatternStatus; execution?: boolean }) { return <div className="insight-gates"><Gate label="THEME" value={gates.theme} /><Gate label="FLOW" value={gates.flow} />{patternStatus || gates.pattern ? <Gate label="PATTERN" value={patternStatus || gates.pattern} /> : null}{execution && gates.execution ? <Gate label="EXECUTION" value={gates.execution} /> : null}</div>; }

function UsLead({ lead, compact = false }: { lead: DrctInsightUsLead; compact?: boolean }) {
  if (!lead.linked || lead.relation_status !== "AVAILABLE") return <div className="insight-us-lead is-empty"><b>US</b><span>-</span></div>;
  const arrow = lead.direction === "UP" ? "↑" : lead.direction === "DOWN" ? "↓" : "→";
  return <div className={`insight-us-lead is-${lead.direction?.toLowerCase() || "flat"}`} title={`${lead.us_theme_name} · 미국 테마강도 ${pct(lead.value)} · 확산 ${lead.breadth_ratio == null ? "-" : `${Math.round(lead.breadth_ratio * 100)}%`}`}><b>US {arrow}</b><span>{lead.us_theme_name} {!compact ? pct(lead.value) : ""}</span><em>{lead.strength === "STRONG" ? "강" : lead.strength === "MODERATE" ? "보통" : "약"}</em></div>;
}

function IntradayBadge({ view }: { view: IntradayView }) { const icon = view.state === "STRENGTHENING" ? "▲" : view.state === "WEAKENING" || view.state === "WARNING" ? "▼" : "→"; return <div className={`insight-intraday is-${view.state.toLowerCase()}`} title={view.reasons.join(" · ")}><span>DRCT VIEW</span><strong>{icon} {view.state}</strong></div>; }
function InsightText({ title, items, warning = false }: { title: string; items: string[]; warning?: boolean }) { if (!items.length) return null; return <section className={`insight-explain ${warning ? "is-warning" : ""}`}><h4>{title}</h4>{items.map((item) => <p key={item}>{warning ? <AlertTriangle size={13} /> : <Check size={13} />}{item}</p>)}</section>; }

function Readiness({ data }: { data: DrctInsightToday }) {
  const sources = Object.entries(data.readiness).filter(([key]) => key !== "overall") as Array<[string, { status: ReadinessStatus; source_date: string | null; note: string }]>;
  return <details className="insight-readiness"><summary>Insight 준비도 <b className={`is-${data.readiness.overall.toLowerCase()}`}>{data.readiness.overall}</b><span>ⓘ</span></summary><div className="insight-readiness-popover"><header><strong>분석 Source 준비 상태</strong><small>Freshness와 별도로 현재 판단 가능 여부를 표시합니다.</small></header><p className="insight-focus-note">Preliminary {data.summary.preliminary_candidate_count}건 중 Focus {data.summary.focus_candidate_count}건</p>{sources.map(([key, source]) => <section key={key}><span>{readinessLabel[key] || key}</span><b className={`is-${source.status.toLowerCase().replace(/_/g, "-")}`}>{source.status}</b><small>{source.note}</small>{key === "us_kr" ? <em>{data.readiness.us_kr.available_count}/{data.readiness.us_kr.linked_count} 연결 · US {data.readiness.us_kr.us_date || "-"} → KR {data.readiness.us_kr.kr_date || "-"}</em> : null}{key === "pattern" ? <em>S {data.readiness.pattern.success_marker_count} · F {data.readiness.pattern.failure_marker_count} · S 준비 {data.readiness.pattern.success_ready_marker_count} · S/F 준비 {data.readiness.pattern.contrast_ready_marker_count} · F 부족 {data.readiness.pattern.failure_shortage_marker_count}</em> : null}</section>)}</div></details>;
}

function reviewCategories(item: DrctInsightReviewItem, view: IntradayView | undefined) {
  const categories = [...item.categories];
  const d0 = item.outcome.d0_return;
  if (d0 != null && view && ((view.state === "STRENGTHENING" && d0 < 0) || (["WEAKENING", "WARNING"].includes(view.state) && d0 >= 3))) categories.push("MISMATCH");
  return [...new Set(categories)];
}

function PostMarketPanel({ data, views, filter, onFilter, onOpen }: { data: DrctInsightToday; views: Record<number, IntradayView>; filter: ReviewFilter; onFilter: (value: ReviewFilter) => void; onOpen: (stockId: number) => void }) {
  const summary = data.outcome_summary;
  const reviews = data.review_queue.filter((item) => {
    const categories = reviewCategories(item, views[item.stock_id]);
    if (filter === "ALL") return true;
    if (filter === "UNRECORDED") return item.outcome.marker_status === "UNRECORDED";
    return categories.includes(filter);
  }).slice(0, 10);
  const scrollTo = (id: string) => document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" });
  return <>
    <nav className="insight-mode-nav" aria-label="장후 Insight 이동"><button type="button" onClick={() => scrollTo("insight-candidates")}>오늘 후보</button><button type="button" onClick={() => scrollTo("insight-review")}>오늘의 복기</button><b>POST-MARKET</b></nav>
    <section className="insight-outcome-panel"><header><div><small>D0 CLOSE REVIEW</small><h3>오늘의 결과</h3></div><Gate label="OUTCOME" value={data.readiness.outcome.status} /></header><dl><div><dt>Focus</dt><dd>{summary.focus_count}</dd></div><div><dt>상승</dt><dd>{summary.positive_count}</dd></div><div><dt>하락</dt><dd>{summary.negative_count}</dd></div><div><dt>평균 D0</dt><dd>{pct(summary.average_d0_return, 2)}</dd></div><div><dt>테마 우위</dt><dd>{summary.theme_outperform_count}/{summary.available_count}</dd></div><div><dt>복기 추천</dt><dd>{summary.review_count}</dd></div></dl>{data.readiness.outcome.status !== "READY" ? <p>{data.readiness.outcome.note} <a href="#/dashboard">가격 데이터 갱신 →</a></p> : null}</section>
    <section className="insight-section insight-review-section" id="insight-review"><div className="insight-section-head"><div><small>Review Queue · HIGH 우선</small><h3>오늘의 복기</h3></div><div className="insight-toggle" aria-label="복기 필터">{([['ALL','전체'],['STRONG','강세'],['WEAK','약세'],['MISMATCH','판단 불일치'],['UNRECORDED','미기록']] as const).map(([key,label]) => <button type="button" key={key} className={filter === key ? "is-active" : ""} onClick={() => onFilter(key)}>{label}</button>)}</div></div><div className="insight-review-list">{reviews.map((item) => {
      const categories = reviewCategories(item, views[item.stock_id]);
      return <article key={item.stock_id} tabIndex={0} onClick={() => onOpen(item.stock_id)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") onOpen(item.stock_id); }}><header><div><small>{item.theme_name || "연결 테마 없음"}</small><h4>{item.stock_name}</h4></div><strong className={`is-${item.priority.toLowerCase()}`}>{item.priority}</strong></header><div className="insight-review-tags"><span>{item.focus_candidate ? "FOCUS" : "MY WATCH"}</span><span>{item.pattern_status}</span>{categories.map((category) => <span key={category}>{category === "STRONG" ? "결과 강세" : category === "WEAK" ? "결과 약세" : category === "MISMATCH" ? "판단 불일치" : category === "PATTERN" ? "Pattern 확인" : "결과 대기"}</span>)}</div><dl><div><dt>D0</dt><dd>{pct(item.outcome.d0_return, 2)}</dd></div><div><dt>테마</dt><dd>{pct(item.outcome.theme_d0_return, 2)}</dd></div><div><dt>상대</dt><dd>{point(item.outcome.relative_return)}%p</dd></div><div><dt>MY STATUS</dt><dd>{item.user_status}</dd></div></dl><p>{item.reasons.join(" · ")}</p><footer><button type="button" onClick={(event) => { event.stopPropagation(); onOpen(item.stock_id); }}>차트 보기</button><a href="#/trading/chart-markers" onClick={(event) => event.stopPropagation()}>Marker 기록</a><span>{item.outcome.marker_status === "UNRECORDED" ? "미기록" : item.outcome.marker_status === "UNDECIDED" ? "미판정 기록" : `${item.outcome.marker_status} 기록`}</span></footer></article>;
    })}</div>{!reviews.length ? <p className="insight-empty">선택한 조건의 복기 대상이 없습니다.</p> : null}</section>
  </>;
}

function InsightDrawer({ stock, view, postMarket, onClose }: { stock: DrctInsightStock; view: IntradayView; postMarket: boolean; onClose: () => void }) {
  const [tab, setTab] = useState<DrawerTab>("summary"); const [period, setPeriod] = useState<NaverStockCandlePeriod>("day");
  useEffect(() => { const handler = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, [onClose]);
  return <div className="insight-drawer-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><aside className="insight-drawer" role="dialog" aria-modal="true" aria-label={`${stock.stock_name} Insight 상세`}><header><div><small>{stock.theme_name || "연결 테마 없음"}</small><h3>{stock.stock_name} <span>{stock.stock_code}</span></h3></div><button type="button" aria-label="닫기" onClick={onClose}><X size={20} /></button></header><nav>{([['summary','요약'],['pattern','Pattern'],['flow','수급'],['chart','차트']] as const).map(([key, label]) => <button type="button" className={tab === key ? "is-active" : ""} key={key} onClick={() => setTab(key)}>{label}</button>)}</nav><div className="insight-drawer-body">
    {postMarket && tab === "summary" && stock.outcome ? <section className="insight-drawer-outcome"><h4>선정 당시 판단 → 오늘 결과</h4><dl className="insight-detail-grid"><div><dt>종가</dt><dd>{stock.outcome.close_price?.toLocaleString() || "-"}</dd></div><div><dt>D0</dt><dd>{pct(stock.outcome.d0_return, 2)}</dd></div><div><dt>테마</dt><dd>{pct(stock.outcome.theme_d0_return, 2)}</dd></div><div><dt>상대성과</dt><dd>{point(stock.outcome.relative_return)}%p</dd></div></dl><p>사용자 판단 <b>{stock.gates.execution || "WAIT"}</b> · Marker <b>{stock.outcome.marker_status === "UNRECORDED" ? "미기록" : stock.outcome.marker_status === "UNDECIDED" ? "미판정 기록" : `${stock.outcome.marker_status} 기록`}</b></p><a className="insight-marker-link" href="#/trading/chart-markers">Marker 기록 화면 <ChevronRight size={14} /></a></section> : null}
    {tab === "summary" ? <><div className={`insight-candidate-level is-${stock.focus_candidate ? "focus" : stock.candidate_level.toLowerCase()}`}><span>후보 등급</span><strong>{stock.focus_candidate ? `FOCUS #${stock.focus_rank}` : stock.candidate_level === "NONE" ? "관찰 중" : stock.candidate_level}</strong><small>{stock.focus_candidate ? "오늘 장중 우선 추적할 Preliminary 후보입니다." : stock.candidate_level === "FINAL" ? "테마·수급·S/F 패턴이 모두 검증된 집중 관찰 후보입니다." : "현재 Gate 조건을 계속 관찰합니다."}</small></div><UsLead lead={stock.us_lead} />{stock.us_lead.linked ? <a className="insight-marker-link" href="#/market-themes?scope=compare&section=watch">한미테마 상세 보기 <ChevronRight size={14} /></a> : null}{!postMarket ? <IntradayBadge view={view} /> : null}<dl className="insight-detail-grid"><div><dt>현재</dt><dd>{pct(stock.change_rate, 2)}</dd></div><div><dt>테마 평균</dt><dd>{pct(stock.theme_change_rate, 2)}</dd></div><div><dt>상대강도</dt><dd>{point(stock.relative_strength)}%p</dd></div><div><dt>최초 진입 대비</dt><dd>{movement(view.initialThemeDelta, "%p") || "-"}</dd></div></dl><GateRow gates={stock.gates} patternStatus={stock.pattern_status} />{!postMarket ? <InsightText title="장중 상태 근거" items={view.reasons} /> : null}<InsightText title="왜 보는가" items={stock.why_items} /><InsightText title="주의" items={stock.warning_items} warning /></> : null}
    {tab === "pattern" ? <><div className="insight-pattern-hero"><div><span>Pattern Edge</span><strong>{stock.pattern_edge == null ? "-" : `${stock.pattern_edge >= 0 ? "+" : ""}${stock.pattern_edge.toFixed(0)}`}</strong></div><dl><div><dt>Success Similarity</dt><dd>{number(stock.success_similarity)}</dd></div><div><dt>Failure Similarity</dt><dd>{number(stock.failure_similarity)}</dd></div></dl></div><p className="insight-sample-note">학습 표본 S {stock.success_sample_count}건 · F {stock.failure_sample_count}/{stock.required_failure_sample_count}건</p>{stock.failure_sample_count < stock.required_failure_sample_count ? <p className="insight-pattern-pending">실패 사례 축적 중 · Pattern Edge 미확정</p> : null}<a className="insight-marker-link" href="#/trading/chart-markers">차트마커 사례 보기 <ChevronRight size={14} /></a></> : null}
    {tab === "flow" ? <><GateRow gates={stock.gates} execution={false} /><dl className="insight-detail-grid"><div><dt>테마강도</dt><dd>{number(stock.theme_strength, 2)}</dd></div><div><dt>직전 대비</dt><dd>{movement(view.themeDelta, "%p") || "-"}</dd></div></dl><p className="insight-muted">상대강도는 현재 종목 등락률에서 동일 실시간 Snapshot의 테마 평균 등락률을 뺀 값입니다.</p></> : null}
    {tab === "chart" ? <><div className="insight-toggle">{([['day','일'],['week','주'],['month','월']] as const).map(([key,label]) => <button type="button" key={key} className={period === key ? "is-active" : ""} onClick={() => setPeriod(key)}>{label}</button>)}</div><img className="insight-chart" src={buildNaverStockCandleChartUrl(stock.stock_code, period, getNaverChartSessionSidcode())} alt={`${stock.stock_name} ${period} 차트`} /></> : null}
  </div></aside></div>;
}

function DrctInsightPage() {
  const [data, setData] = useState<DrctInsightToday | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const [sort, setSort] = useState<StockSort>("candidate"); const [themeId, setThemeId] = useState<number | null>(null); const [candidateFilter, setCandidateFilter] = useState<CandidateFilter>("FOCUS"); const [watchFilter, setWatchFilter] = useState<WatchFilter>("ALL"); const [reviewFilter, setReviewFilter] = useState<ReviewFilter>("ALL"); const [selected, setSelected] = useState<DrctInsightStock | null>(null); const [views, setViews] = useState<Record<number, IntradayView>>({});
  const requestRef = useRef(0); const abortRef = useRef<AbortController | null>(null); const initialSnapshotRef = useRef<InsightSnapshot | null>(null); const previousSnapshotRef = useRef<InsightSnapshot | null>(null); const currentSnapshotRef = useRef<InsightSnapshot | null>(null); const stateRef = useRef<Record<number, IntradayState>>({}); const watchSectionRef = useRef<HTMLElement | null>(null); const stockSectionRef = useRef<HTMLElement | null>(null);

  const load = useCallback(async () => {
    const requestId = ++requestRef.current; abortRef.current?.abort(); const controller = new AbortController(); abortRef.current = controller; setLoading(true); setError("");
    try {
      let next = await repositories.drctInsight.today(controller.signal); if (requestId !== requestRef.current) return;
      if (next.market_mode === "POST_MARKET" && !next.evaluation_captured) next = await repositories.drctInsight.captureTodayEvaluation(controller.signal);
      const snapshot = snapshotOf(next); const previous = currentSnapshotRef.current; if (!initialSnapshotRef.current) initialSnapshotRef.current = snapshot;
      const nextViews = Object.fromEntries(next.stocks.map((row) => [row.stock_id, intradayView(row, previous, initialSnapshotRef.current, stateRef.current[row.stock_id])]));
      stateRef.current = Object.fromEntries(Object.entries(nextViews).map(([key, value]) => [Number(key), value.state])); previousSnapshotRef.current = previous; currentSnapshotRef.current = snapshot;
      setViews(nextViews); setData(next); setThemeId((current) => current && next.themes.some((row) => row.theme_id === current) ? current : null); setSelected((current) => current ? next.stocks.find((row) => row.stock_id === current.stock_id) || null : null);
    } catch (cause) { if (requestId === requestRef.current && !controller.signal.aborted) setError(cause instanceof Error ? cause.message : "Insight를 불러오지 못했습니다."); }
    finally { if (requestId === requestRef.current) setLoading(false); }
  }, []);
  useEffect(() => { void load(); return () => abortRef.current?.abort(); }, [load]);

  const stocks = useMemo(() => {
    const rows = (data?.stocks || []).filter((row) => { if (themeId && row.theme_id !== themeId) return false; if (candidateFilter === "FOCUS") return row.focus_candidate; if (candidateFilter === "ALL") return true; return row.candidate_level === candidateFilter; });
    const level = (value: CandidateLevel) => value === "FINAL" ? 2 : value === "PRELIMINARY" ? 1 : 0;
    return [...rows].sort((a, b) => sort === "change" ? (b.change_rate ?? -999) - (a.change_rate ?? -999) : sort === "pattern" ? (b.pattern_edge ?? -999) - (a.pattern_edge ?? -999) || b.success_similarity - a.success_similarity : Number(b.final_candidate) - Number(a.final_candidate) || Number(b.focus_candidate) - Number(a.focus_candidate) || (a.focus_rank ?? 99999) - (b.focus_rank ?? 99999) || level(b.candidate_level) - level(a.candidate_level) || b.convergence_level - a.convergence_level || b.success_similarity - a.success_similarity).slice(0, 30);
  }, [candidateFilter, data, sort, themeId]);
  const watches = useMemo(() => (data?.my_watch || []).filter((row) => watchFilter === "ALL" || row.gates.execution === watchFilter), [data, watchFilter]);
  const addWatch = async (stock: DrctInsightStock) => { await repositories.watchlist.bulkAdd({ stock_ids: [stock.stock_id], memo: "오늘의 DrCT Insight" }); await load(); };
  const updateWatch = async (row: DrctInsightWatchItem, value: string) => { await repositories.watchlist.update(row.watchlist_id, { status: executionStatus[value] || "관심" }); await load(); };
  const jumpCandidate = (filter: CandidateFilter) => { setCandidateFilter(filter); stockSectionRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }); }; const jumpReady = () => { setWatchFilter("READY"); watchSectionRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }); };
  const fallbackView: IntradayView = { state: "STABLE", reasons: ["변화 비교 대기"], themeDelta: null, themeChangeDelta: null, initialThemeDelta: null, breadthDelta: null, executionAssist: "KEEP_WATCH" };

  const postMarket = data?.market_mode === "POST_MARKET";
  return <div className="drct-insight-page"><PageHeader title="오늘의 DrCT Insight" description={postMarket ? "Focus 후보의 D0 결과와 복기 우선순위를 확인합니다." : "Focus 후보와 장중 강화·유지·약화 변화를 추적합니다."} action={<button type="button" className="btn btn-secondary" disabled={loading} onClick={() => void load()}><RefreshCw size={14} /> {loading ? "갱신 중" : "새로고침"}</button>} />
    <div className={`insight-sticky${postMarket ? " is-post" : ""}`}>{postMarket ? <><button type="button" onClick={() => jumpCandidate("FOCUS")}><span>Focus</span><strong>{data?.outcome_summary.focus_count ?? "-"}</strong></button><button type="button"><span>상승</span><strong>{data?.outcome_summary.positive_count ?? "-"}</strong></button><button type="button"><span>하락</span><strong>{data?.outcome_summary.negative_count ?? "-"}</strong></button><button type="button" onClick={() => document.getElementById("insight-review")?.scrollIntoView({ behavior: "smooth" })}><span>복기</span><strong>{data?.outcome_summary.review_count ?? "-"}</strong></button><button type="button" onClick={() => watchSectionRef.current?.scrollIntoView({ behavior: "smooth" })}><span>MY WATCH</span><strong>{data?.summary.my_watch_count ?? "-"}</strong></button></> : <><button type="button"><span>관찰테마</span><strong>{data?.summary.observed_theme_count ?? "-"}</strong></button><button type="button" onClick={() => jumpCandidate("FOCUS")}><span>Focus</span><strong>{data?.summary.focus_candidate_count ?? "-"}</strong></button><button type="button" onClick={() => jumpCandidate("FINAL")}><span>Final</span><strong>{data?.summary.final_candidate_count ?? "-"}</strong></button><button type="button" onClick={() => watchSectionRef.current?.scrollIntoView({ behavior: "smooth" })}><span>MY WATCH</span><strong>{data?.summary.my_watch_count ?? "-"}</strong></button><button type="button" onClick={jumpReady}><span>READY</span><strong>{data?.summary.ready_count ?? "-"}</strong></button></>}{data ? <Readiness data={data} /> : null}<p>{postMarket ? <>평균 D0 <b>{pct(data?.outcome_summary.average_d0_return ?? null, 2)}</b></> : <>Preliminary <b>{data?.summary.preliminary_candidate_count ?? "-"}</b></>} · 갱신 <b>{data?.summary.last_updated_at?.slice(5,16) || "-"}</b></p></div>
    {error ? <div className="insight-error">{error}<button type="button" onClick={() => void load()}>다시 시도</button></div> : null}<div className="insight-freshness">{data && Object.entries(data.freshness).map(([key,value]) => <span key={key}>{freshnessLabel[key] || key} <b>{value?.slice(5,16) || "-"}</b></span>)}</div>
    {data?.market_mode === "POST_MARKET" ? <PostMarketPanel data={data} views={views} filter={reviewFilter} onFilter={setReviewFilter} onOpen={(stockId) => { const stock = data.stocks.find((row) => row.stock_id === stockId); if (stock) setSelected(stock); }} /> : <div className="insight-mode-nav"><b>{data?.market_mode || "INTRADAY"}</b><span>{data?.market_mode === "PRE_MARKET" ? "오늘 후보를 준비합니다." : "장중 변화는 Session Memory에서 비교합니다."}</span></div>}
    <section className="insight-section"><div className="insight-section-head"><div><small>US D-1 → 장중 변화</small><h3>오늘의 테마</h3></div>{themeId ? <button type="button" onClick={() => setThemeId(null)}>선택 해제</button> : null}</div><div className="insight-theme-grid">{data?.themes.map((theme: DrctInsightTheme) => { const previous = previousSnapshotRef.current?.themes[theme.theme_id]; const themeDelta = delta(theme.theme_strength ?? theme.change_rate, previous?.strength ?? previous?.changeRate ?? null); return <article key={theme.theme_id} role="button" tabIndex={0} className={themeId === theme.theme_id ? "is-selected" : ""} onClick={() => setThemeId(theme.theme_id)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); setThemeId(theme.theme_id); } }}><header><div><small>관찰 {theme.observation_rank ? `#${theme.observation_rank}` : "-"}</small><h4>{theme.theme_name}</h4></div><strong className={(theme.change_rate || 0) >= 0 ? "is-up" : "is-down"}>{pct(theme.change_rate)}</strong></header><UsLead lead={theme.us_lead} /><div className="insight-theme-motion"><span>강도 {number(theme.theme_strength, 2)} <b>{movement(themeDelta, "%p")}</b></span><span>확산 {theme.valid_stock_count}/{theme.linked_stock_count}</span></div><GateRow gates={theme.gates} execution={false} /><p className="insight-why-line" title={theme.why_items.join(" · ")}>{theme.why_items.join(" · ") || "판단 데이터 확인 중"}</p><footer title={`Preliminary ${theme.preliminary_candidate_count}`}><span>연결 <b>{theme.linked_candidate_count}</b></span><span>Focus <b>{theme.focus_candidate_count}</b></span><span>Final <b>{theme.final_candidate_count}</b></span></footer></article>; })}</div></section>
    <section className="insight-section" id="insight-candidates" ref={stockSectionRef}>
      <div className="insight-section-head"><div><small>{postMarket ? "선정 당시 판단 → D0 결과" : "Preliminary → Focus"}</small><h3>오늘의 종목</h3></div><div className="insight-controls"><div className="insight-toggle" aria-label="후보 등급 필터">{([['ALL','전체'],['FOCUS','Focus'],['PRELIMINARY','Preliminary'],['FINAL','Final']] as const).map(([key,label]) => <button type="button" className={candidateFilter === key ? "is-active" : ""} key={key} onClick={() => setCandidateFilter(key)}>{label}</button>)}</div><div className="insight-toggle" aria-label="정렬 기준">{([['candidate','종합 후보'],['pattern','Pattern'],['change','등락률']] as const).map(([key,label]) => <button type="button" className={sort === key ? "is-active" : ""} key={key} onClick={() => setSort(key)}>{label}</button>)}</div></div></div>
      <div className="insight-stock-grid">{stocks.map((stock) => {
        const view = views[stock.stock_id] || fallbackView;
        return <article key={stock.stock_id} role="button" tabIndex={0} className={`is-${stock.focus_candidate ? "focus" : stock.candidate_level.toLowerCase()}`} onClick={() => setSelected(stock)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); setSelected(stock); } }}>
          <header><div><small>{stock.theme_name || "연결 테마 없음"}</small><h4>{stock.stock_name}</h4></div><div className="insight-stock-actions">{stock.focus_candidate ? <em>FOCUS #{stock.focus_rank}</em> : stock.candidate_level !== "NONE" ? <em>{stock.candidate_level}</em> : null}<button type="button" className="insight-star" aria-label="MY WATCH 등록" onClick={(event) => { event.stopPropagation(); void addWatch(stock); }}><Star size={17} /></button></div></header>
          <UsLead lead={stock.us_lead} compact />
          <div className="insight-focus-metrics"><span>Pattern <b>{stock.pattern_status}</b></span><span>S <b>{number(stock.success_similarity)}</b></span><span title={postMarket ? "종목 D0 - 테마 D0" : "현재 종목 등락률 - 해당 테마 평균 등락률"}>{postMarket ? "상대" : "RS"} <b>{point(postMarket ? stock.outcome?.relative_return ?? null : stock.relative_strength)}</b></span></div>
          {postMarket ? <div className="insight-card-outcome"><dl><div><dt>종가</dt><dd>{stock.outcome?.close_price?.toLocaleString() || "-"}</dd></div><div><dt>D0</dt><dd>{pct(stock.outcome?.d0_return ?? null, 2)}</dd></div><div><dt>테마</dt><dd>{pct(stock.outcome?.theme_d0_return ?? null, 2)}</dd></div></dl><p>마지막 DrCT View <b>{currentSnapshotRef.current && previousSnapshotRef.current ? view.state : "-"}</b> · MY STATUS <b>{stock.gates.execution || "WAIT"}</b></p></div> : <><IntradayBadge view={view} /><p className="insight-warning-line">{view.reasons[0]}</p></>}
          <footer>{postMarket ? <><span>{stock.outcome?.marker_status === "UNRECORDED" ? "Marker 미기록" : stock.outcome?.marker_status === "UNDECIDED" ? "Marker 미판정" : `Marker ${stock.outcome?.marker_status} 기록`}</span><span>{stock.outcome?.status === "NOT_READY" ? "결과 계산 중" : pct(stock.outcome?.d0_return ?? null, 2)}</span></> : <><span>{view.executionAssist === "CONSIDER_READY" ? "READY 전환 검토" : view.executionAssist === "CAUTION" ? "변화 주의" : "WATCH 유지"}</span><span>{pct(stock.change_rate, 2)}</span></>}</footer>
        </article>;
      })}</div>{data && !stocks.length ? <p className="insight-empty">조건에 맞는 종목 후보가 없습니다.</p> : null}
    </section>
    <section className="insight-section" ref={watchSectionRef}><div className="insight-section-head"><div><small>사용자 상태와 DrCT View 분리</small><h3>MY WATCH</h3></div><div className="insight-toggle">{([['ALL','전체'],['READY','READY'],['WATCH','WATCH'],['TRIGGERED','TRIGGERED']] as const).map(([key,label]) => <button type="button" className={watchFilter === key ? "is-active" : ""} key={key} onClick={() => setWatchFilter(key)}>{label}</button>)}</div></div><div className="insight-watch-list insight-watch-list--phase3b">{watches.map((row) => { const view = views[row.stock_id] || fallbackView; return <article key={row.watchlist_id} onClick={() => setSelected(row)}><div><small>{row.theme_name || "연결 테마 없음"}</small><h4>{row.stock_name}</h4><span>MY STATUS <b>{row.gates.execution || "WAIT"}</b></span></div><IntradayBadge view={view} /><dl><div><dt>현재</dt><dd>{pct(row.change_rate)}</dd></div><div><dt>테마</dt><dd>{pct(row.theme_change_rate)}</dd></div><div><dt>상대</dt><dd>{point(row.relative_strength)}</dd></div><div><dt>확산 변화</dt><dd>{movement(view.breadthDelta) || "-"}</dd></div></dl><Gate label="PATTERN" value={row.pattern_status} /><div className="insight-watch-actions"><select aria-label={`${row.stock_name} 실행 상태`} value={row.gates.execution || "WAIT"} onClick={(event) => event.stopPropagation()} onChange={(event) => void updateWatch(row, event.target.value)}><option value="WAIT">WATCH</option><option value="READY">READY</option><option value="TRIGGERED">TRIGGERED</option><option value="INVALID">INVALID</option></select>{view.executionAssist === "CONSIDER_READY" && row.gates.execution !== "READY" ? <button type="button" onClick={(event) => { event.stopPropagation(); void updateWatch(row, "READY"); }}>READY로 변경</button> : null}<button type="button" onClick={(event) => { event.stopPropagation(); setSelected(row); }}>상세</button></div></article>; })}</div></section>
    {selected ? <InsightDrawer stock={selected} view={views[selected.stock_id] || fallbackView} postMarket={data?.market_mode === "POST_MARKET"} onClose={() => setSelected(null)} /> : null}
  </div>;
}

export default DrctInsightPage;
