import { useCallback, useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { ArrowRight, CheckCircle2, ChevronDown, ChevronRight, CircleAlert, Database, RefreshCw, Settings2, Sparkles, X } from "lucide-react";

import { ReviewChart, normalizeReviewChart } from "@/pages/ChartMarkerReviewPage";
import { repositories } from "@/services";
import type { ChartMarkerEvent, ChartMarkerReviewChart, ChartMarkerReviewEvent } from "@/types/chartMarker";
import type { DrctMarkerAutoLearningSummary, DrctMarkerLearningCase, DrctMarkerLearningMarker, DrctMarkerLearningOutcomes, DrctMarkerLearningReviewCase, DrctMarkerLearningReviewDetail, DrctMarkerPatternSignature, DrctMarkerRelatedSearch, DrctMarkerSimilarityValidation } from "@/types/drctStockSignal";

type MainTab = "status" | "review";
type CaseFilter = "ALL" | "S" | "F" | "UNDECIDED";
const errorText = (reason:unknown) => reason instanceof Error ? reason.message : "요청을 처리하지 못했습니다.";
const learningLabel = (value:DrctMarkerAutoLearningSummary["learning_status"]|DrctMarkerLearningMarker["learning_status"]) => value === "TESTABLE" ? "시그널 검증 가능" : value === "EARLY" ? "학습 중" : "사례 부족";
const recommendationLabel = (value:DrctMarkerAutoLearningSummary["recommendation_readiness"]) => value === "READY" ? "시그널 검증 가능" : value === "RESEARCH" ? "학습 중" : "사례 부족";
const score = (value:number|null) => value == null ? "-" : `${value.toFixed(1)}점`;

export default function MarkerLearningWorkspace(){
  const [markers,setMarkers]=useState<DrctMarkerLearningMarker[]>([]);
  const [markerId,setMarkerId]=useState<number|null>(null);
  const [expandedGroupId,setExpandedGroupId]=useState<number|null>(null);
  const [summary,setSummary]=useState<DrctMarkerAutoLearningSummary|null>(null);
  const [tab,setTab]=useState<MainTab>("status");
  const [reviewCases,setReviewCases]=useState<DrctMarkerLearningReviewCase[]>([]);
  const [advancedOpen,setAdvancedOpen]=useState(false), [casesOpen,setCasesOpen]=useState(false);
  const [reviewDetail,setReviewDetail]=useState<DrctMarkerLearningReviewDetail|null>(null);
  const [busy,setBusy]=useState(false), [error,setError]=useState<string|null>(null);
  const summaryRequest=useRef(0);

  const loadCatalog=useCallback(async()=>{const {items}=await repositories.drctStockSignals.markerLearningMarkers();setMarkers(items);setMarkerId(current=>items.some(item=>item.marker_id===current)?current:items[0]?.marker_id??null);setExpandedGroupId(current=>items.some(item=>item.marker_group_id===current)?current:items[0]?.marker_group_id??null);},[]);
  useEffect(()=>{loadCatalog().catch((reason)=>setError(errorText(reason)));},[loadCatalog]);
  const loadSummary=useCallback(async()=>{if(!markerId)return;const request=++summaryRequest.current;setBusy(true);setError(null);try{const next=await repositories.drctStockSignals.markerAutoLearningSummary(markerId);if(request===summaryRequest.current)setSummary(next);}catch(reason){if(request===summaryRequest.current)setError(errorText(reason));}finally{if(request===summaryRequest.current)setBusy(false);}},[markerId]);
  useEffect(()=>{setSummary(null);setTab("status");setReviewCases([]);setReviewDetail(null);void loadSummary();},[loadSummary]);
  useEffect(()=>{if(tab!=="review"||!markerId)return;let active=true;setBusy(true);repositories.drctStockSignals.markerLearningReviewCases(markerId).then(result=>{if(active)setReviewCases(result.items);}).catch(reason=>{if(active)setError(errorText(reason));}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[tab,markerId]);
  const groups=useMemo(()=>Array.from(new Map(markers.map(item=>[item.marker_group_id,{id:item.marker_group_id,name:item.marker_group_name,color:item.marker_group_color}])).values()),[markers]);
  const refresh=async()=>{setBusy(true);try{await Promise.all([loadCatalog(),loadSummary()]);if(tab==="review"&&markerId){const result=await repositories.drctStockSignals.markerLearningReviewCases(markerId);setReviewCases(result.items);}}finally{setBusy(false);}};
  const selectMarker=(marker:DrctMarkerLearningMarker)=>{setExpandedGroupId(marker.marker_group_id);setMarkerId(marker.marker_id);};

  return <section className="drct-auto-learning">
    <header className="drct-auto-learning-head"><div><h2>차트마커 자동학습</h2><p>성공으로 복기된 Marker를 자동으로 학습하고, 같은 패턴을 찾을 준비 상태를 확인합니다.</p></div><div className="drct-learning-head-actions"><button className="btn btn-secondary" type="button" disabled={!markerId} onClick={()=>setCasesOpen(true)}>선택 Marker 사례</button><button className="btn btn-secondary" type="button" disabled={!markerId} onClick={()=>setAdvancedOpen(true)}><Settings2 size={15}/> 알고리즘 상세</button><button className="drct-icon-button" type="button" aria-label="새로고침" disabled={busy} onClick={()=>void refresh()}><RefreshCw size={16}/></button></div></header>
    {error?<p className="drct-signal-inline-error" role="alert">{error}</p>:null}
    <div className="drct-learning-accordion">{groups.map(group=>{const groupMarkers=markers.filter(item=>item.marker_group_id===group.id),reviewCount=groupMarkers.reduce((total,item)=>total+item.review_recommended_count,0),expanded=expandedGroupId===group.id;return <section key={group.id} className={`drct-marker-group-section ${expanded?"is-expanded":""}`}><button type="button" className="drct-marker-group-header" aria-expanded={expanded} onClick={()=>setExpandedGroupId(group.id)}><span><i style={{background:group.color}}/><strong>{group.name}</strong></span><span className="drct-group-header-meta">{reviewCount?<em>검토 {reviewCount}</em>:null}<b>{groupMarkers.length}개</b><ChevronDown size={16}/></span></button>{expanded?<div className="drct-marker-grid">{groupMarkers.map(marker=><button type="button" key={marker.marker_id} className={markerId===marker.marker_id?"is-selected":""} onClick={()=>selectMarker(marker)}><i style={{background:marker.marker_group_color}}>{marker.marker_symbol}</i><span><strong>{marker.marker_name.replace(/^.*? - /,"")}</strong><small>성공 학습 {marker.s_count}건</small><em>{learningLabel(marker.learning_status)}</em></span>{marker.review_recommended_count?<b>검토 {marker.review_recommended_count}</b>:null}</button>)}</div>:null}</section>;})}</div>
    {summary?<><section className="drct-learning-summary"><div className="drct-learning-selected"><i style={{background:summary.marker.marker_group_color}}>{summary.marker.marker_symbol}</i><div><span>{summary.marker.marker_group_name}</span><h3>{summary.marker.marker_name}</h3><p>성공(S) 사례를 자동 학습합니다.</p></div></div>{[["성공 학습",`${summary.success_count}건`],["학습 사용",`${summary.learning_case_count}건`],["검토 필요",`${summary.review_recommended_count}건`],["추천 준비",recommendationLabel(summary.recommendation_readiness)]].map(([label,value])=><article key={String(label)}><span>{label}</span><strong>{value}</strong></article>)}</section>
    <nav className="drct-marker-learning-tabs" aria-label="차트마커 자동학습 메뉴"><button type="button" className={tab==="status"?"is-active":""} onClick={()=>setTab("status")}>학습 현황</button><button type="button" className={tab==="review"?"is-active":""} onClick={()=>setTab("review")}>검토 필요 {summary.review_recommended_count?<em>{summary.review_recommended_count}</em>:null}</button></nav>
    {tab==="status"?<LearningStatus summary={summary}/>:<ReviewList rows={reviewCases} busy={busy} onOpen={async row=>{if(!markerId)return;try{setReviewDetail(await repositories.drctStockSignals.markerLearningReviewDetail(markerId,row.chart_marker_event_id));}catch(reason){setError(errorText(reason));}}}/>}</>:<div className="drct-neutral-empty"><Database size={22}/><strong>차트마커를 선택해 주세요.</strong></div>}
    {advancedOpen&&markerId?<AlgorithmDrawer markerId={markerId} onClose={()=>setAdvancedOpen(false)}/>:null}
    {casesOpen&&markerId?<AllCasesDrawer markerId={markerId} onClose={()=>setCasesOpen(false)}/>:null}
    {reviewDetail&&markerId?<ReviewDecisionModal markerId={markerId} detail={reviewDetail} onClose={()=>setReviewDetail(null)} onDecided={async()=>{setReviewDetail(null);await refresh();}}/>:null}
  </section>;
}

function LearningStatus({summary}:{summary:DrctMarkerAutoLearningSummary}){
  const canValidate=summary.learning_case_count>=5;
  return <div className="drct-learning-status-panel"><section className="drct-auto-status-card"><div className="drct-pulse-icon"><Sparkles size={19}/></div><div><span>자동학습 중</span><h3>성공 사례 {summary.learning_case_count}건을 학습에 사용 중입니다.</h3><p>새로운 성공 사례가 추가되면 패턴 기준이 자동으로 갱신됩니다.</p></div><dl><div><dt>마지막 계산</dt><dd>{summary.calculated_at.replace("T"," ")}</dd></div></dl></section><div className="drct-learning-status-grid"><article className={canValidate?"is-ready":"is-pending"} title="현재 학습 사례 수로 종목 시그널 검증을 시작할 수 있는지 보여줍니다."><header>{canValidate?<CheckCircle2/>:<CircleAlert/>}<span>추천 준비</span></header><strong>{recommendationLabel(summary.recommendation_readiness)}</strong><p>{canValidate?"현재 종목에서 같은 패턴을 찾는 시그널 검증을 시작할 수 있습니다.":"성공 학습 사례가 더 필요합니다."}</p></article><article><header><Sparkles/><span>성공 패턴 일관성</span></header><strong>{score(summary.consistency_median)}</strong><p>과거 성공 사례끼리의 유사도</p></article></div>{summary.data_incomplete_count?<p className="drct-learning-notice"><CircleAlert size={15}/> 성공 사례 중 {summary.data_incomplete_count}건은 과거 가격 데이터가 부족해 아직 학습에 사용하지 않습니다.</p>:null}</div>;
}

function ReviewList({rows,busy,onOpen}:{rows:DrctMarkerLearningReviewCase[];busy:boolean;onOpen:(row:DrctMarkerLearningReviewCase)=>void}){return <div className="drct-learning-review-panel"><header><div><h3>검토가 필요한 사례 {rows.length}건</h3><p>성공 사례 중 기존 패턴과 차이가 큰 사례입니다. 확인 전까지도 자동학습에는 포함됩니다.</p></div></header>{busy?<p>검토 사례를 계산하는 중입니다.</p>:rows.length?<div className="drct-review-list">{rows.map(row=><button type="button" key={row.chart_marker_event_id} onClick={()=>onOpen(row)}><span className="drct-review-stock"><strong>{row.stock_name}</strong><small>{row.stock_code}</small></span><span>{row.d0}</span><span>유사도 {row.pattern_similarity.toFixed(1)}</span><em>주요 차이 3개</em><ChevronRight size={16}/></button>)}</div>:<div className="drct-neutral-empty"><CheckCircle2 size={25}/><strong>현재 검토가 필요한 성공 사례가 없습니다.</strong><p>성공 사례가 5건 미만이면 이상 사례를 판정하지 않습니다.</p></div>}</div>;}

function AlgorithmDrawer({markerId,onClose}:{markerId:number;onClose:()=>void}){
  const [signature,setSignature]=useState<DrctMarkerPatternSignature|null>(null),[validation,setValidation]=useState<DrctMarkerSimilarityValidation|null>(null),[outcomes,setOutcomes]=useState<DrctMarkerLearningOutcomes|null>(null),[references,setReferences]=useState<DrctMarkerRelatedSearch[]>([]),[error,setError]=useState("");
  useEffect(()=>{Promise.all([repositories.drctStockSignals.markerPatternSignature(markerId),repositories.drctStockSignals.markerSimilarityValidation(markerId),repositories.drctStockSignals.markerLearningOutcomes(markerId),repositories.drctStockSignals.markerRelatedSearches(markerId)]).then(([s,v,o,r])=>{setSignature(s);setValidation(v);setOutcomes(o);setReferences(r.items);}).catch(reason=>setError(errorText(reason)));},[markerId]);
  return <Drawer title="알고리즘 상세" subtitle="개발·검증용 정보입니다. 기본 자동학습 상태에는 영향을 주지 않습니다." onClose={onClose}>{error?<p className="drct-signal-inline-error">{error}</p>:!signature?<p>알고리즘 정보를 계산하는 중입니다.</p>:<div className="drct-algorithm-details"><section className="drct-algorithm-policy"><h4>S 중심 학습 정책</h4><p>성공(S) · 기본 데이터 준비 · 수동 제외 아님인 사례만 추천용 패턴 기준에 사용합니다. 실패(F)는 품질 비교에만 사용하고 미판정은 학습하지 않습니다.</p></section><details><summary>패턴 기준과 버전</summary><dl><div><dt>학습 사례</dt><dd>{signature.case_count}건</dd></div><div><dt>Feature Schema</dt><dd>v{signature.feature_schema_version}</dd></div><div><dt>Signature</dt><dd>v{signature.pattern_signature_version}</dd></div><div><dt>Similarity</dt><dd>v{signature.similarity_algorithm_version}</dd></div></dl></details><details><summary>성공사례 LOO 검증</summary><p>평가 {validation?.evaluated_count??0}건 · 중앙 {score(validation?.distribution?.median??null)} · P25~P75 {score(validation?.distribution?.p25??null)} ~ {score(validation?.distribution?.p75??null)}</p></details><details><summary>Feature 분포</summary><div className="drct-feature-compact">{signature.features.map(feature=><span key={feature.key}><b>{feature.label}</b> 중앙 {feature.median.toFixed(2)} · IQR {feature.iqr.toFixed(2)}</span>)}</div></details><details><summary>실패 사례 비교</summary><p>성공 {outcomes?.labels.S??0}건 · 실패 {outcomes?.labels.F??0}건. 실패 사례는 추천용 기준에 포함하지 않습니다.</p></details><details><summary>관련 검색식</summary>{references.length?<ul>{references.map(item=><li key={item.search_id}>{item.search_name} · v{item.current_version_no}</li>)}</ul>:<p>연결된 참고 검색식이 없습니다.</p>}</details><p className="drct-runtime-policy">계산 결과와 사례별 유사도는 저장하지 않고 요청 시 계산합니다.</p></div>}</Drawer>;
}

function AllCasesDrawer({markerId,onClose}:{markerId:number;onClose:()=>void}){const [filter,setFilter]=useState<CaseFilter>("ALL"),[rows,setRows]=useState<DrctMarkerLearningCase[]>([]),[busy,setBusy]=useState(true);useEffect(()=>{setBusy(true);repositories.drctStockSignals.markerLearningCases(markerId,filter).then(result=>setRows(result.items)).finally(()=>setBusy(false));},[markerId,filter]);return <Drawer title="전체 차트마커 사례" subtitle="학습 대상과 무관하게 원본 복기 사례를 조회합니다." onClose={onClose}><div className="drct-case-filter">{([['ALL','전체'],['S','성공'],['F','실패'],['UNDECIDED','미판정']] as const).map(([key,label])=><button key={key} type="button" className={filter===key?"is-active":""} onClick={()=>setFilter(key)}>{label}</button>)}</div>{busy?<p>사례를 불러오는 중입니다.</p>:<div className="drct-all-case-list">{rows.map(row=><article key={row.chart_marker_event_id}><div><strong>{row.stock_name}</strong><small>{row.stock_code}</small></div><span>{row.d0}</span><b>{row.review_result??"미판정"}</b><em>{row.review_result==="S"?(row.learning_decision==="EXCLUDE"?"학습 제외":row.core_status==="READY"?"자동학습 포함":"데이터 부족"):"학습 대상 아님"}</em></article>)}</div>}</Drawer>;}

function ReviewDecisionModal({markerId,detail,onClose,onDecided}:{markerId:number;detail:DrctMarkerLearningReviewDetail;onClose:()=>void;onDecided:()=>Promise<void>}){
  const [chart,setChart]=useState<ChartMarkerReviewChart|null>(null),[reviewEvent,setReviewEvent]=useState<ChartMarkerReviewEvent|null>(null),[events,setEvents]=useState<ChartMarkerEvent[]>([]),[busy,setBusy]=useState(false),[reason,setReason]=useState("");
  useEffect(()=>{Promise.all([repositories.chartMarkers.reviewChart(detail.stock_id,detail.d0,60,20),repositories.chartMarkers.reviewEvents(markerId),repositories.chartMarkers.listStockEvents(detail.stock_id)]).then(([chartResult,eventResult,stockEvents])=>{setChart(normalizeReviewChart(chartResult,60,20));setReviewEvent(eventResult.items.find(item=>item.id===detail.chart_marker_event_id)??null);setEvents(stockEvents.items);});},[detail,markerId]);
  const decide=async(decision:"INCLUDE"|"EXCLUDE")=>{setBusy(true);try{await repositories.drctStockSignals.putMarkerLearningDecision(markerId,detail.chart_marker_event_id,decision,reason);await onDecided();}finally{setBusy(false);}};
  return <div className="drct-signal-modal-backdrop"><section className="drct-signal-modal drct-learning-review-modal" role="dialog" aria-modal="true"><header><div><h3>{detail.stock_name} · {detail.d0}</h3><p>성공 사례가 일반적인 성공 패턴과 다른 이유를 차트와 함께 확인합니다.</p></div><button type="button" onClick={onClose}><X size={19}/></button></header><div className="drct-review-modal-body"><section className="drct-review-reason"><div><b>S</b><strong>유사도 {detail.pattern_similarity.toFixed(1)}점</strong><span>검토 전까지 자동학습 포함</span></div><p>{detail.reason}</p></section>{reviewEvent?<ReviewChart data={chart} reviewEvent={reviewEvent} loading={!chart} markerEvents={events} showD0Marker onContextMenu={()=>{}}/>:<div className="chart-marker-chart-skeleton"/>}<section className="drct-top-differences"><h4>일반 성공 패턴과 가장 다른 항목</h4>{detail.top_feature_differences.map(item=><article key={item.key}><div><strong>{item.label}</strong><small>차이 {item.robust_distance.toFixed(2)}</small></div><span>실제 {item.case_value.toFixed(2)}{item.unit}</span><ArrowRight size={14}/><span>일반 {item.signature_median.toFixed(2)}{item.unit}</span></article>)}</section><label className="drct-decision-reason">판단 메모 (선택)<input value={reason} maxLength={120} onChange={event=>setReason(event.target.value)} placeholder="포함 또는 제외 판단 근거"/></label></div><footer><button className="btn btn-secondary" type="button" disabled={busy} onClick={()=>void decide("INCLUDE")}>학습에 계속 포함</button><button className="btn btn-primary danger" type="button" disabled={busy} onClick={()=>void decide("EXCLUDE")}>이번 학습에서 제외</button></footer></section></div>;
}

function Drawer({title,subtitle,onClose,children}:{title:string;subtitle:string;onClose:()=>void;children:ReactNode}){return <div className="drct-drawer-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)onClose();}}><aside className="drct-learning-drawer" role="dialog" aria-modal="true"><header><div><h3>{title}</h3><p>{subtitle}</p></div><button type="button" onClick={onClose}><X size={19}/></button></header><div className="drct-learning-drawer-body">{children}</div></aside></div>;}
